Add beepboop overlay
gentoo/api-gentoo-org pull request #305
Opened 2020-10-18 21:40 UTC by IgorDrozniak

2020-11-02 22:40 UTC, mgorny requested changes

2020-11-02 22:40 UTC, mgorny commented on files/overlays/repositories.xml
> +  <name>beepboop</name>
Please match the indentation to other entries.

2020-11-02 22:40 UTC, mgorny commented on files/overlays/repositories.xml
> +  <homepage>https://gitlab.com/igordrozniak/beepboop.git</homepage>
I think the canonical homepage URL is without `.git`.

2020-11-02 22:40 UTC, mgorny commented on files/overlays/repositories.xml
> +    <email>igordrozniak@disroot.org</email>
This e-mail does not seem to be registered on Gentoo Bugzilla.

2020-11-02 22:40 UTC, mgorny commented on files/overlays/repositories.xml
> +
Please do not add extra whitespace.

2020-11-03 14:03 UTC, IgorDrozniak commented on files/overlays/repositories.xml
> +
fixed

2020-11-03 14:03 UTC, IgorDrozniak commented on files/overlays/repositories.xml
> +    <email>igordrozniak@disroot.org</email>
fixed

2020-11-03 14:03 UTC, IgorDrozniak commented on files/overlays/repositories.xml
> +  <homepage>https://gitlab.com/igordrozniak/beepboop.git</homepage>
fixed

2020-11-03 14:03 UTC, IgorDrozniak commented on files/overlays/repositories.xml
> +  <name>beepboop</name>
fixed

2020-11-03 14:09 UTC, mgorny commented on files/overlays/repositories.xml
> +    <homepage>https://gitlab.com/igordrozniak/beepboop</homepage>
This and sources still seem to differ in case, causing unnecessary redirect.

2022-04-14 07:41 UTC, jsmolic commented
ping

2022-04-27 19:51 UTC, jsmolic commented
Closing due to inactivity. Feel free to open a new PR.

2022-04-27 19:51 UTC, closed without merging