repositories: Add overseerr
gentoo/api-gentoo-org pull request #354
Opened 2021-01-04 23:46 UTC by chriscpritchard

Hello,

please could I add this repository to the list.

Thanks

2021-01-04 23:50 UTC, mgorny requested changes

2021-01-04 23:50 UTC, mgorny commented on files/overlays/repositories.xml
> +      <name>overseerr</name>
`<name/>` and `repo_name` inside the repository must match. Please settle on one name and update both.

2021-01-04 23:57 UTC, chriscpritchard commented on files/overlays/repositories.xml
> +      <name>overseerr</name>
updated and squashed the commits

2021-01-21 08:44 UTC, mgorny approved these changes
I'm sorry about missing your update. I'll merge it now.

2021-01-21 08:44 UTC, closed without merging