used_free_uidgids.sh: new script to output information regarding free
gentoo/api-gentoo-org pull request #359
Opened 2021-01-19 19:35 UTC by jkroonza

and used UID and GID values.

Signed-off-by: Jaco Kroon <jaco@iewc.co.za>

2021-01-19 19:42 UTC, juippis commented
Mostly that can it be stored in `/bin` or does some cron job run all the files there periodically. I believe this script should be hosted within api.git where it can be ran anytime someone is choosing a new UID+GID. Since it's getting increasingly difficult to find the next available UID+GID set manually.

2021-01-20 08:39 UTC, mgorny reviewed
Writing such things in bash cause my brain to melt.

2021-01-20 08:39 UTC, mgorny commented on bin/used_free_uidgids.sh
> +#output uid
Leftover?

2021-01-20 08:39 UTC, mgorny commented on bin/used_free_uidgids.sh
> +	#echo "ui=$ui (${uids[$ui]}..${ranges_uid[${uids[$ui]}]}), gi=$gi (${gids[$gi]}..${ranges_gid[${gids[$gi]}]}), idbase=$idbase, re=$re"
?

2021-01-20 10:19 UTC, jkroonza commented on bin/used_free_uidgids.sh
> +#output uid
Yea, including the output function itself.  Which I'd prefer to leave in there in case debug is required again at a later stage.

2021-01-20 10:20 UTC, jkroonza commented on bin/used_free_uidgids.sh
> +	#echo "ui=$ui (${uids[$ui]}..${ranges_uid[${uids[$ui]}]}), gi=$gi (${gids[$gi]}..${ranges_gid[${gids[$gi]}]}), idbase=$idbase, re=$re"
again useful for debug, but happy to nuke.

2021-01-20 17:15 UTC, mgorny requested changes
Always use `${brackets}` when referencing variables, wrap some long lines, combine `[[ ... ]]` when possible.

2021-01-20 17:15 UTC, mgorny commented on bin/used_free_uidgids.sh
> +! tty -s <&1 && colour_USED= && colour_FREE= && colour_RESERVED= && colour_RESET=
Please use `if`s for multiple assignments, and avoid weird logic.

2021-01-20 17:15 UTC, mgorny commented on bin/used_free_uidgids.sh
> +tty -s && [[ -r "${def_infile}" ]] && exec <"${def_infile}"
I suppose it would be nice to provide some stderr output here. After all, you're going to block on stdin depending on cwd.

2021-01-20 17:15 UTC, mgorny commented on bin/used_free_uidgids.sh
> +		if [[ $k -le $range_start ]] && [[ $range_end -le ${ranges[$k]} ]]; then
```suggestion
		if [[ $k -le ${range_start} && ${range_end} -le ${ranges[$k]} ]]; then
```

2021-01-21 05:01 UTC, jkroonza commented on bin/used_free_uidgids.sh
> +		if [[ $k -le $range_start ]] && [[ $range_end -le ${ranges[$k]} ]]; then
Fixed elsewhere too ... might have overdone it now.

2021-01-21 05:04 UTC, jkroonza commented on bin/used_free_uidgids.sh
> +tty -s && [[ -r "${def_infile}" ]] && exec <"${def_infile}"
jkroon@plastiekpoot ~/projects/api-gentoo-org/bin (used-free-uidgids) $ rm ../files/uid-gid.txt 
jkroon@plastiekpoot ~/projects/api-gentoo-org/bin (used-free-uidgids) $ ./used_free_uidgids.sh 
Reading from stdin (which happens to be a tty, you should pipe input file to stdin)

Depends more on location of script compared to uid-gid.txt (previous line tracks location of script and then relative to that try to find uid-gid.txt:

jkroon@plastiekpoot ~/projects/api-gentoo-org (used-free-uidgids) $ git checkout files/uid-gid.txt
Updated 1 path from the index
jkroon@plastiekpoot ~/projects/api-gentoo-org (used-free-uidgids) $ bin/used_free_uidgids.sh 
#ID               UID       GID
0..11            USED      USED

2021-01-22 09:49 UTC, mgorny commented on bin/used_free_uidgids.sh
> +tty -s && [[ -r "${def_infile}" ]] && exec <"${def_infile}" || echo "Reading from stdin (which happens to be a tty, you should pipe input file to stdin)" >&2
This too.

2021-01-22 09:49 UTC, mgorny commented on bin/used_free_uidgids.sh
> +			[[ ${range_end} -lt ${ranges[${k}]} ]] && ranges[${range_end}+1]=${ranges[${k}]} && reasons[${range_end}+1]=${reasons[${k}]}
And this, and all other long chains.

2021-01-26 13:50 UTC, mgorny commented on bin/used_free_uidgids.sh
> +		if [[ ${k} -le ${range_start} ]] && [[ ${range_end} -le ${ranges[${k}]} ]]; then
```suggestion
		if [[ ${k} -le ${range_start} && ${range_end} -le ${ranges[${k}]} ]]; then
```

2021-01-26 13:50 UTC, mgorny commented on bin/used_free_uidgids.sh
> +			[[ ${type} == RESERVED ]] && return # USED takes prescedence RESERVED.
```suggestion
			[[ ${type} == RESERVED ]] && return # USED takes precedence over RESERVED.
```

?

2021-01-26 13:50 UTC, mgorny commented on bin/used_free_uidgids.sh
> +	declare -n reasons="reason_$1"
Make the quoting consistent, please.

2021-01-26 13:50 UTC, mgorny commented on bin/used_free_uidgids.sh
> +		while [[ -n "${ranges[${e}+1]:+set}" ]] && [[ "${reasons[${k}]}" == "${reasons[${e}+1]}" ]]; do
```suggestion
		while [[ -n "${ranges[${e}+1]:+set}" && "${reasons[${k}]}" == "${reasons[${e}+1]}" ]]; do
```

and more below.

2021-01-26 13:50 UTC, mgorny commented on bin/used_free_uidgids.sh
> +			unset ranges[${e}+1]
```suggestion
			unset "ranges[${e}+1]"
```

2021-01-26 17:09 UTC, monsieurp commented on bin/used_free_uidgids.sh
> +	[[ -n "${debug}" ]] && echo "ui=${ui} (${uids[${ui}]}..${ranges_uid[${uids[${ui}]}]}), gi=${gi} (${gids[${gi}]}..${ranges_gid[${gids[${gi}]}]}), idbase=${idbase}, re=${re}"
This line gives me headaches.

2021-01-26 17:57 UTC, jkroonza commented on bin/used_free_uidgids.sh
> +	[[ -n "${debug}" ]] && echo "ui=${ui} (${uids[${ui}]}..${ranges_uid[${uids[${ui}]}]}), gi=${gi} (${gids[${gi}]}..${ranges_gid[${gids[${gi}]}]}), idbase=${idbase}, re=${re}"
well, it's basically a dump of the relevant variables ... not saying it's not nasty, but it's going to be nasty no matter what.

2021-02-04 06:00 UTC, juippis commented
What's the status here? Everything seems to have been resolved. @ulm @mgorny

2021-02-08 14:16 UTC, juippis approved these changes

2021-02-09 07:20 UTC, juippis commented
f3639b24b860a182d375e5617fa77755b9f9a5a6 thank you!

2021-02-09 07:20 UTC, closed without merging