repositories: Add dinolay
gentoo/api-gentoo-org pull request #459
Opened 2022-01-01 02:54 UTC by TruncatedDinosour

2022-01-02 10:59 UTC, jsmolic requested changes
Please keep the list sorted

2022-01-02 18:43 UTC, TruncatedDinosour commented
> Please keep the list sorted

What list? How sorted?

2022-01-02 18:44 UTC, TruncatedDinosour commented
> Please keep the list sorted

okay

2022-01-02 18:54 UTC, TruncatedDinosour commented
> Please keep the list sorted

done

2022-01-02 19:03 UTC, TruncatedDinosour commented
> Please keep the list sorted

done

2022-01-02 19:21 UTC, jsmolic commented on files/overlays/repositories.xml
> +    <description lang="en">My gentoo overlay for me to not need to use multiple ones</description>
This should be changed to "dinolay's overlay" or something similar

2022-01-02 22:40 UTC, TruncatedDinosour commented on files/overlays/repositories.xml
> +    <description lang="en">My gentoo overlay for me to not need to use multiple ones</description>
Sure

2022-01-02 22:42 UTC, TruncatedDinosour commented on files/overlays/repositories.xml
> +    <description lang="en">My gentoo overlay for me to not need to use multiple ones</description>
wait, which part, the description or the name?

2022-01-02 22:48 UTC, TruncatedDinosour commented
@jsmolic fixed

2022-01-03 08:35 UTC, jsmolic approved these changes
Thanks, I'm going to squash and merge

2022-01-03 08:36 UTC, closed without merging